### ISSUE TITLE
cannot find type SendableMetatype in scope

### ISSUE THREAD

**Issue by CamJN** [apple/swift-argument-parser#827]
I cannot compile this package (specifically the bash completion step) with the latest swift compiler available from the CLT and the `SDKROOT` set to `/Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk`, like homebrew does.

**ArgumentParser version:** `1.6.1`
**Swift version:** 
```
swift-driver version: 1.127.14.1
Apple Swift version 6.2 (swiftlang-6.2.0.19.9 clang-1700.3.19.1)
Target: x86_64-apple-macosx15.0
```
**CLT version:** `26.0.0.0.1.1757719676`
**macOS version:** `15.7.1 (24G231)`

### Checklist
- [ ] If possible, I've reproduced the issue using the `main` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-argument-parser/issues)

### Steps to Reproduce
```
git clone git@github.com:CamJN/aliasPath.git
cd aliasPath
export SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk
make
```

### Expected behaviour
`swift-argument-parser` can compile with swift 6.2 compiler, and macOS 15 SDK.

### Actual behaviour
```
...snip
 23 [8/10] Compiling ArgumentParser BashCompletionsGenerator.swift
 24 /private/tmp/alias-path-20251013-91126-xovrpd/aliasPath-1.0.0/.build/checkouts/swift-argument-parser/Sources/ArgumentParser/Utilities/SwiftExtensions.swift:14:45: error: cannot find type 'SendableMetatype' in scope
 25 12 | #if compiler(>=6.2)
 26 13 | /// Designates a type as having a sendable metatype.
 27 14 | @_marker public protocol _SendableMetatype: SendableMetatype {}
 28    |                                             `- error: cannot find type 'SendableMetatype' in scope
 29 15 | #else
 30 16 | @_marker public protocol _SendableMetatype {}
 31 make: *** [/private/tmp/alias-path-20251013-91126-xovrpd/aliasPath-1.0.0/.build/x86_64-apple-macosx/release/aliasPath] Error 1
 32 
```

**Comment by grigorye** [comment]
@CamJN Try to see if you have SDKROOT set in your environment/unset it. It was set in my case (potentially by Homebrew), unsetting it did the job.
```
$ xcrun --show-toolchain-path
/Applications/Xcode-26.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
$ xcrun --show-sdk-version
2025-12-09 11:21:05.197 xcodebuild[55678:234385643] Writing error result bundle to /var/folders/46/t8ph0gt50vx9_v5ydd53rlsc0000gp/T/ResultBundle_2025-09-12_11-21-0005.xcresult
xcodebuild: error: SDK "/Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk" cannot be located.
xcrun: error: unable to lookup item 'SDKVersion' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk'
$ env|grep SDKROOT
SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk
```

**Comment by CamJN** [comment]
That's literally what I said… 

> I cannot compile this package (specifically the bash completion step) with the latest swift compiler available from the CLT and the SDKROOT set to /Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk, like homebrew does.

I reported it because homebrew sets SDKROOT to the sdk for the host version of macOS but this requires setting the SDKROOT to 26.0's sdk or later. Unsetting works on tahoe and setting the sdkroot to 26.0's sdk works on earlier macOS. But instead of making people do that it'd be better to make this package compatible.

**Comment by grigorye** [comment]
> That's literally what I said…
> 
> > I cannot compile this package (specifically the bash completion step) with the latest swift compiler available from the CLT and the SDKROOT set to /Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk, like homebrew does.
> 
> I reported it because homebrew sets SDKROOT to the sdk for the host version of macOS but this requires setting the SDKROOT to 26.0's sdk or later. Unsetting works on tahoe and setting the sdkroot to 26.0's sdk works on earlier macOS. But instead of making people do that it'd be better to make this package compatible.

Ah, sorry - I did not read it carefully. I wonder if it's not a problem in swift-argument-parser but some kind of incompatibility between the compiler and sdk... (I observe it with the compiler from Xcode 26.0.1).

**Comment by grigorye** [comment]
In any case, Homebrew setting SDKROOT does not look good to me.

**Comment by mickeyl** [comment]
Just hit the same w/ https://github.com/mickeyl/core-bluetooth-tool/issues/8 — had to go all the way back to 1.5.1 to fix it, since all of 1.6.x contains the same SendableMetatype code.
